repos:
- repo: https://github.com/pre-commit/mirrors-autopep8
  rev: ''  # Specify a specific version/tag/commit or leave empty for the latest version
  hooks:
    - id: autopep8
      exclude: '^./module-3/session-9/'  # Specify files or patterns to exclude, '^$' excludes nothing (all files will be checked)
      args: [--verbose]

- repo: https://github.com/PyCQA/flake8
  rev: 6.0.0
  hooks:
  - id: flake8
    args: [--ignore=E501]
    exclude: '^./module-3/session-9/'